name = "edgekit"
main = "src/main.ts"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2025-06-01"
account_id = "your-account-id-here"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "edgekit-db"
database_id = "your-database-id-here"

[[r2_buckets]]
binding = 'BUCKET'
bucket_name = 'edgekit-bucket'

[[kv_namespaces]]
binding = "SESSION_CACHE"
id = "session-cache"

[dev]
port = 8787

[vars]
BACKEND_URL = ""
FRONTEND_URL = ""
GITHUB_CLIENT_ID = ""
BETTER_AUTH_URL = ""
